### PR TITLE
Added a setting to set page title

### PR DESCRIPTION
**Pull request by MCMic**
Hello, 

This allows to set the title of the maraschino page, which is often used as the tab name in browsers.

### CODE REVIEW

**Comment by MCMic** [comment]
Any problem with this pull request? Why not merging it?

**Comment by MCMic** [comment]
Any update?

**Comment by onedr0p** [comment]
Mr. @mrkipling are you alive? ^_^

**Comment by gugahoi** [comment]
Ha! I missed this one, sorry guys. Looks all good so I'll merge it in without testing as it is simple enough. Please let me know if any issues arise.

**Pull request merged**
